name: CyanAccelSprint
version: 1.1
author: Cyanoure
main: ga.cyanoure.cyanaccelsprint.Main
website: http://www.cyanoure.ga/
description: Sprint Accelerator Plugin
commands:
    casreload:
        description: Reload config
        permission: cyanaccelsprint.admin