name: CyanAccelSprint
version: @version@
main: ga.cyanoure.cyanaccelsprint.Main
author: Cyanoure
website: http://www.cyanoure.ga/
description: Sprint Accelerator Plugin
commands:
  casreload:
    description: Reload config
    permission: cyanaccelsprint.admin
  togglesprint:
    description: Toggle sprint acceleration
    permission: cyanaccelsprint.toggle