name: CyanAccelSprint
version: @version@
main: hu.kozelkaricsi.cyanaccelsprint.Main
author: Cyanoure
website: https://kozelkaricsi.hu/
description: Sprint Accelerator Plugin
commands:
  casreload:
    description: Reload config
    permission: cyanaccelsprint.admin
  togglesprint:
    description: Toggle sprint acceleration
    permission: cyanaccelsprint.toggle